apiVersion: v1
kind: Namespace
metadata:
  name: kairos-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builds.ops.kairos.io
spec:
  group: ops.kairos.io
  names:
    kind: Build
    listKind: BuildList
    plural: builds
    singular: build
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Build 是 builds API 的架构
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BuildSpec 定义 Build 的期望状态
            properties:
              callback:
                description: Callback 定义完成后调用的 webhook
                properties:
                  authToken:
                    description: AuthToken 是用于身份验证的可选令牌
                    type: string
                  url:
                    description: URL 是构建完成后调用的 Webhook URL
                    type: string
                type: object
              contextUrl:
                description: ContextUrl 是 git 仓库的 URL
                type: string
              dockerfile:
                default: Dockerfile
                description: Dockerfile 是 Dockerfile 的路径
                type: string
              outputImage:
                description: OutputImage 是目标镜像（例如 registry.com/user/image:tag）
                type: string
              pushSecret:
                description: PushSecret 是包含注册表凭据的密钥名称
                type: string
              revision:
                default: master
                description: Revision 是 git 版本（分支、标签、提交）
                type: string
            required:
            - contextUrl
            - outputImage
            type: object
          status:
            description: BuildStatus 定义 Build 的观察状态
            properties:
              callbackStatus:
                description: CallbackStatus 指示回调是否成功
                type: string
              completionTime:
                description: CompletionTime 是构建完成的时间
                format: date-time
                type: string
              jobRef:
                description: JobRef 是对 Kubernetes Job 的引用
                type: string
              phase:
                description: Phase 是构建的当前状态
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kairos-controller-manager
  namespace: kairos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kairos-manager-role
rules:
- apiGroups: ["ops.kairos.io"]
  resources: ["builds"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ops.kairos.io"]
  resources: ["builds/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["ops.kairos.io"]
  resources: ["builds/finalizers"]
  verbs: ["update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kairos-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kairos-manager-role
subjects:
- kind: ServiceAccount
  name: kairos-controller-manager
  namespace: kairos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kairos-controller-manager
  namespace: kairos-system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: kairos-controller-manager
      terminationGracePeriodSeconds: 10
